//==================================================
// This file contains the Excluded objects
// Generated By User: marcom
// Format Version: 2
// Date: Thu Apr 30 23:45:32 2026
// ExclMode: default
//==================================================
CHECKSUM: "4204327600 2641222745"
INSTANCE: APB_TOP.apb_sys.timer0
Block 17 "2384835014" "o_pready <= 1'b1;"
Block 32 "2877838170" "count_pready <= (count_pready + 3'(1));"
Block 26 "1303962961" "count_pready <= (count_pready + 3'(1));"
Block 19 "82394467" "o_pready <= 1'b1;"
CHECKSUM: "4204327600 255725671"
INSTANCE: APB_TOP.apb_sys.timer0
Toggle i_paddr [31] "logic i_paddr[31:0]"
Toggle i_paddr [9] "logic i_paddr[31:0]"
Toggle i_paddr [10] "logic i_paddr[31:0]"
Toggle i_paddr [11] "logic i_paddr[31:0]"
Toggle i_paddr [12] "logic i_paddr[31:0]"
Toggle i_paddr [13] "logic i_paddr[31:0]"
Toggle i_paddr [14] "logic i_paddr[31:0]"
Toggle i_paddr [15] "logic i_paddr[31:0]"
Toggle i_paddr [16] "logic i_paddr[31:0]"
Toggle i_paddr [17] "logic i_paddr[31:0]"
Toggle i_paddr [18] "logic i_paddr[31:0]"
Toggle i_paddr [19] "logic i_paddr[31:0]"
Toggle i_paddr [20] "logic i_paddr[31:0]"
Toggle i_paddr [21] "logic i_paddr[31:0]"
Toggle i_paddr [22] "logic i_paddr[31:0]"
Toggle i_paddr [23] "logic i_paddr[31:0]"
Toggle i_paddr [24] "logic i_paddr[31:0]"
Toggle i_paddr [25] "logic i_paddr[31:0]"
Toggle i_paddr [26] "logic i_paddr[31:0]"
Toggle i_paddr [27] "logic i_paddr[31:0]"
Toggle i_paddr [28] "logic i_paddr[31:0]"
Toggle i_paddr [29] "logic i_paddr[31:0]"
Toggle i_paddr [30] "logic i_paddr[31:0]"
Toggle count_pready "logic count_pready[2:0]"
CHECKSUM: "4204327600 794004958"
INSTANCE: APB_TOP.apb_sys.timer0
Condition 3 "749831401" "((timer_idx < NUM_TIMERS) ? t_reg[timer_idx] : '0) 1 -1"
Condition 11 "2261204902" "(o_pready && i_psel && timer_addr_error) 1 -1"
Condition 6 "2848339164" "(count_pready == 3'(WAIT_WRITE)) 1 -1"
Condition 10 "3904449166" "(count_pready == 3'(WAIT_READ)) 1 -1"
Condition 1 "3395633530" "(i_psel && i_penable && i_pwrite && o_pready) 1 -1"
Condition 7 "3839851344" "(((!i_pwrite)) && i_psel) 1 -1"
CHECKSUM: "4204327600 1574615848"
INSTANCE: APB_TOP.apb_sys.timer0
Branch 1 "561625408" "(!i_prstn)" (1) "(!i_prstn) 0,1,1,-,-,-,-,-,-,-,-,-"
Branch 1 "561625408" "(!i_prstn)" (11) "(!i_prstn) 0,0,-,-,-,0,-,-,1,0,-,0"
Branch 1 "561625408" "(!i_prstn)" (7) "(!i_prstn) 0,0,-,-,-,1,0,0,-,-,-,-"
Branch 1 "561625408" "(!i_prstn)" (3) "(!i_prstn) 0,1,0,1,0,-,-,-,-,-,-,-"
Branch 1 "561625408" "(!i_prstn)" (2) "(!i_prstn) 0,1,0,1,1,-,-,-,-,-,-,-"
