class apb_driver extends uvm_driver #(apb_transaction);
    `uvm_component_utils(apb_driver)

    virtual apb_external_if vif;

    int tx_count1 = 0; // Count of transactions generated by the driver
    int tx_count2 = 0; // Count of transactions completed by the driver
    int wait_cycles;
    localparam int READY_TIMEOUT_CYCLES = 1000;

    // Standard UVM component constructor
    function new(string name = "apb_driver", uvm_component parent);
        super.new(name, parent);
        `uvm_info("APB_DRV", "APB Driver initialized", UVM_MEDIUM)
    endfunction

    // Retrieve virtual interface
    virtual function void build_phase(uvm_phase phase);
        super.build_phase(phase);
        `uvm_info("APB_DRV", "Checking VIF", UVM_MEDIUM)
        
        // Fetch the virtual interface from the config DB
        if (!uvm_config_db#(virtual apb_external_if)::get(this, "", "vif", vif)) begin
            `uvm_fatal("DRV_NO_VIF", {"Virtual interface must be set for: ", get_full_name(), ".vif"})
        end
        
        `uvm_info("APB_DRV", "VIF present", UVM_MEDIUM)
    endfunction

    virtual function void connect_phase(uvm_phase phase);
        super.connect_phase(phase);
    endfunction

    // Run phase, reset DUT and drive transactions
    virtual task run_phase(uvm_phase phase);
        super.run_phase(phase);
        
        // Execute Reset Sequence
        reset_dut();

        // Main Stimulus Loop
        `uvm_info("APB_DRV", "Running stimulus loop", UVM_MEDIUM)
        forever begin
            // Fetch transaction from  sequencer
            seq_item_port.get_next_item(req);

            // Wait until DUT is ready/idle
            wait_cycles = 0;
            while (vif.ready !== 1'b1) begin
                @(posedge vif.clk);
                wait_cycles++;
                if (wait_cycles >= READY_TIMEOUT_CYCLES) begin
                    `uvm_fatal("DRV_TIMEOUT", $sformatf("Timeout waiting for ready=1 before tx #%0d", tx_count1 + 1))
                end
            end

            // Drive transaction onto interface
            vif.rw <= req.rw;
            vif.data_in <= (req.rw) ? req.data_in : '0; // Only drive data for write transactions
            vif.addr <= req.addr;
            vif.start <= 1; // Assert start to initiate the transaction
            
            //--------------------------------
            //  LOGGING 
            // Log the stimulus using UVM_INFO
            `uvm_info("APB_DRV", $sformatf("TX#%0d %s / SLAVE=%0d REG=%0d ADDR=0x%08x %s%s", 
                tx_count1 + 1, (req.rw ? "WRITE" : "READ"), req.slave_sel, req.reg_sel, req.addr, 
                (req.rw ? "DATA_IN=" : ""), (req.rw ? $sformatf("0x%08x", req.data_in) : "")), UVM_HIGH)

            @(posedge vif.clk);
            vif.start <= 0; // Deassert start after one cycle
            tx_count1++;

            // Wait for busy phase entry
            wait_cycles = 0;
            while (vif.ready !== 1'b0) begin
                @(posedge vif.clk);
                wait_cycles++;
                if (wait_cycles >= READY_TIMEOUT_CYCLES) begin
                    `uvm_fatal("APB_DRV", $sformatf("Timeout waiting for ready=0 after issuing tx #%0d", tx_count1))
                end
            end

            // Wait for completion
            wait_cycles = 0;
            while (vif.ready !== 1'b1) begin
                @(posedge vif.clk);
                wait_cycles++;
                if (wait_cycles >= READY_TIMEOUT_CYCLES) begin
                    `uvm_fatal("APB_DRV", $sformatf("Timeout waiting for ready=1 completion for tx #%0d", tx_count1))
                end
            end

            tx_count2++; // Increment count of completed transactions

            // Signal to the sequencer that the transaction is complete
            seq_item_port.item_done();
        end
    endtask

    // Reset task
    task reset_dut();
        `uvm_info("APB_DRV", "Resetting DUT", UVM_MEDIUM)
        vif.start <= 0;
        vif.rw <= 0;
        vif.data_in <= '0;
        vif.addr <= '0;

        // Synchronize to external reset generation before driving traffic.
        wait (vif.rst_n === 1'b1);
        wait (vif.rst_n === 1'b0);
        wait (vif.rst_n === 1'b1);
        @(posedge vif.clk);
        `uvm_info("APB_DRV", "Reset sequence complete.", UVM_MEDIUM)
    endtask

endclass : apb_driver