class DRIVER;
	int tx_count1; // Count of transactions generated by the driver
	int tx_count2; // Count of transactions completed by the driver
	localparam int READY_TIMEOUT_CYCLES = 1000;

	virtual apb_external_if vif;
	mailbox gen2drv;

	function new(virtual apb_external_if ext_if, mailbox gen2drv);
		this.vif = ext_if;
		this.gen2drv = gen2drv;
		tx_count1 = 0;
		tx_count2 = 0;
	endfunction

	task reset();
		$display("[DRIVER] Resetting DUT...");
		vif.start <= 0;
		vif.rw <= 0;
		vif.data_in <= '0;
		vif.addr <= '0;

		// Synchronize to external reset generation before driving traffic.
		wait (vif.rst_n === 1'b1);
		wait (vif.rst_n === 1'b0);
		wait (vif.rst_n === 1'b1);
		@(posedge vif.clk);
	endtask

	task start();
		int wait_cycles;
		$display("[DRIVER] STARTED");
		forever begin
			TRANSACTION tx;
			gen2drv.get(tx); // Wait for a transaction from the generator
			$display("[DRIVER] RX TX#%0d: %s ADDR=0x%08x DATA=0x%08x", tx_count1 + 1, (tx.rw ? "WRITE" : "READ "), tx.addr, tx.data_in);

			// Wait until DUT is ready/idle.
			wait_cycles = 0;
			while (vif.ready !== 1'b1) begin
				@(posedge vif.clk);
				wait_cycles++;
				if (wait_cycles >= READY_TIMEOUT_CYCLES) begin
					$fatal(1, "[DRIVER] Timeout waiting for ready=1 before tx #%0d", tx_count1 + 1);
				end
			end

			// Drive the transaction onto the interface
			vif.rw <= tx.rw;
			vif.data_in <= (tx.rw) ? tx.data_in : '0; // Only drive data for write transactions
			vif.addr <= tx.addr;
			vif.start <= 1; // Assert start to initiate the transaction
			$display("[DRIVER]   SINGLE: TX#%0d %s ADDR=0x%08x DATA=0x%08x", tx_count1 + 1, (tx.rw ? "WRITE" : "READ "), tx.addr, tx.data_in);
			@(posedge vif.clk);
			vif.start <= 0; // Deassert start after one cycle
			tx_count1++;

			// Wait for busy phase entry then completion.
			wait_cycles = 0;
			while (vif.ready !== 1'b0) begin
				@(posedge vif.clk);
				wait_cycles++;
				if (wait_cycles >= READY_TIMEOUT_CYCLES) begin
					$fatal(1, "[DRIVER] Timeout waiting for ready=0 after issuing tx #%0d", tx_count1);
				end
			end

			wait_cycles = 0;
			while (vif.ready !== 1'b1) begin
				@(posedge vif.clk);
				wait_cycles++;
				if (wait_cycles >= READY_TIMEOUT_CYCLES) begin
					$fatal(1, "[DRIVER] Timeout waiting for ready=1 completion for tx #%0d", tx_count1);
				end
			end

			tx_count2++;						// Increment count of completed transactions
		end
		$display("[DRIVER] FINISHED");
	endtask

endclass : DRIVER