class DRIVER;
	int tx_count1; // Count of transactions generated by the driver
	int tx_count2; // Count of transactions completed by the driver
	int wait_cycles;
	localparam int READY_TIMEOUT_CYCLES = 1000;

	virtual apb_external_if vif;
	mailbox gen2drv;

	function new(virtual apb_external_if ext_if, mailbox gen2drv);
		this.vif = ext_if;
		this.gen2drv = gen2drv;
		tx_count1 = 0;
		tx_count2 = 0;
	endfunction

	task reset();
		$display("[DRIVER] Resetting DUT...");
		vif.start <= 0;
		vif.rw <= 0;
		vif.data_in <= '0;
		vif.addr <= '0;

		// Synchronize to external reset generation before driving traffic.
		wait (vif.rst_n === 1'b0);
		wait (vif.rst_n === 1'b1);
		repeat (2) @(posedge vif.clk);
	endtask

	task chain_driver(TRANSACTION chain_tx);
		TRANSACTION next_tx;
		int chain_length = chain_tx.chain_length;
		int remaining;

		// Wait until DUT is ready/idle.
		wait_cycles = 0;
		while (vif.ready !== 1'b1) begin
			@(posedge vif.clk);
			wait_cycles++;
			if (wait_cycles >= READY_TIMEOUT_CYCLES) begin
				$fatal(1, "[DRIVER] Timeout waiting for ready=1 before tx #%0d", tx_count1);
			end
		end

		// Drive the original chain transaction onto the interface
		vif.rw <= chain_tx.rw;
		vif.data_in <= (chain_tx.rw) ? chain_tx.data_in : '0; // Only drive data for write transactions
		vif.addr <= chain_tx.addr;
		vif.start <= 1; // Assert start to initiate the transaction for the whole chain
		$display("[DRIVER]   HEAD: TX#%0d %s ADDR=0x%08x", tx_count1, (chain_tx.rw ? "WRITE" : "READ "), chain_tx.addr);
		@(posedge vif.clk);
		vif.start <= 0;

		// head transaction was counted when received by start()

		// Use a local remaining counter derived from the chain length so the driver
		// does not depend on per-transaction flags that can be modified elsewhere.
		remaining = chain_length;
		remaining--; // we've just driven the head transaction

		while (remaining > 0) begin

			// Wait for busy phase entry then completion.
			wait_cycles = 0;
			while (vif.ready !== 1'b0) begin
				@(posedge vif.clk);
				wait_cycles++;
				if (wait_cycles >= READY_TIMEOUT_CYCLES) begin
					$fatal(1, "[DRIVER] Timeout waiting for ready=0 after issuing chained tx #%0d", tx_count1);
				end
			end

			vif.start <= 1; 

			wait_cycles = 0;
			while (vif.ready !== 1'b1) begin
				@(posedge vif.clk);
				wait_cycles++;
				if (wait_cycles >= READY_TIMEOUT_CYCLES) begin
					$fatal(1, "[DRIVER] Timeout waiting for ready=1 completion for chained tx #%0d", tx_count1);
				end
			end

			tx_count2++;					// Increment count of completed transactions


			gen2drv.get(next_tx); 			// Get the next transaction in the chain from the generator
			// Count the chained transaction as received/issued immediately
			tx_count1++;

			// Drive the next transaction onto the interface
			vif.rw <= next_tx.rw;
			vif.data_in <= (next_tx.rw) ? next_tx.data_in : '0; // Only drive data for write transactions
			vif.addr <= next_tx.addr;
			@(posedge vif.clk);
			vif.start <= 0;
			remaining--; // one less chained transaction to drive
		end

		// Final: Wait for busy phase entry then completion.
		wait_cycles = 0;
		while (vif.ready !== 1'b0) begin
			@(posedge vif.clk);
			wait_cycles++;
			if (wait_cycles >= READY_TIMEOUT_CYCLES) begin
				$fatal(1, "[DRIVER] Timeout waiting for ready=0 after issuing chained tx #%0d", tx_count1);
			end
		end

		wait_cycles = 0;
		while (vif.ready !== 1'b1) begin
			@(posedge vif.clk);
			wait_cycles++;
			if (wait_cycles >= READY_TIMEOUT_CYCLES) begin
				$fatal(1, "[DRIVER] Timeout waiting for ready=1 completion for chained tx #%0d", tx_count1);
			end
		end

		tx_count2++;					// Increment count of completed transactions

		$display("[DRIVER]   CHAIN DONE: (len=%0d)", chain_length);

		vif.start <= 0; // Deassert start after chain completion

	endtask

	task normal_driver(TRANSACTION tx);
		// Wait until DUT is ready/idle.
		wait_cycles = 0;
		while (vif.ready !== 1'b1) begin
			@(posedge vif.clk);
			wait_cycles++;
			if (wait_cycles >= READY_TIMEOUT_CYCLES) begin
				$fatal(1, "[DRIVER] Timeout waiting for ready=1 before tx #%0d", tx_count1);
			end
		end

		// Drive the transaction onto the interface
		vif.rw <= tx.rw;
		vif.data_in <= (tx.rw) ? tx.data_in : '0; // Only drive data for write transactions
		vif.addr <= tx.addr;
		vif.start <= 1; // Assert start to initiate the transaction
		$display("[DRIVER]   SINGLE: TX#%0d %s ADDR=0x%08x", tx_count1, (tx.rw ? "WRITE" : "READ "), tx.addr);
		@(posedge vif.clk);
		vif.start <= 0; // Deassert start after one cycle

		// Wait for busy phase entry then completion.
		wait_cycles = 0;
		while (vif.ready !== 1'b0) begin
			@(posedge vif.clk);
			wait_cycles++;
			if (wait_cycles >= READY_TIMEOUT_CYCLES) begin
				$fatal(1, "[DRIVER] Timeout waiting for ready=0 after issuing tx #%0d", tx_count1);
			end
		end

		wait_cycles = 0;
		while (vif.ready !== 1'b1) begin
			@(posedge vif.clk);
			wait_cycles++;
			if (wait_cycles >= READY_TIMEOUT_CYCLES) begin
				$fatal(1, "[DRIVER] Timeout waiting for ready=1 completion for tx #%0d", tx_count1);
			end
		end

		tx_count2++;						// Increment count of completed transactions

	endtask

	task start();
		$display("[DRIVER] STARTED");
		forever begin
			TRANSACTION tx;
			gen2drv.get(tx); // Wait for a transaction from the generator
			// Count the received/issued transaction immediately so TEST waits align with generator counts
			tx_count1++;
			$display("[DRIVER] RX TX#%0d: %s ADDR=0x%08x", tx_count1, (tx.rw ? "WRITE" : "READ "), tx.addr);

			if (tx.chain_en == 1) begin
				$display("[DRIVER]   -> CHAIN(len=%0d)", tx.chain_length);
				chain_driver(tx);
			end else begin
				normal_driver(tx);
			end

		end
		$display("[DRIVER] FINISHED");
	endtask

endclass : DRIVER